version: '3.2'

services:
  iff:
    build:
      context: .
      dockerfile: Dockerfile
    image: iff:latest
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated
      - type: volume
        source: bundle
        target: /usr/local/bundle
    ports:
      - '3000:3000'
    environment:
      - CURRENT_CONFERENCE=IFF2019
      - NEW_CFP_ENABLED=true
      - PUBLISHABLE_KEY=pk_test_TYooMQauvdEDq54NiTphI7jx
      - SECRET_KEY=sk_test_4eC39HqLyjWDarjtT1zdp7dc
    command: ["tail", "-f", "/dev/null"]

volumes:
  bundle:
